name: 'Carson Man!'
favicon: null
layout_spectrum: 0.25003
typography_spectrum: 0.53803
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#17161b'
    - '#e4ced5'
    - '#741e31'
    - '#b07c5e'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
