name: 'Carson Man!'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85388
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafafa'
    - '#17161b'
    - '#e4ced5'
    - '#741e31'
    - '#b07c5e'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
