name: 'Carson Man!'
favicon: null
layout_spectrum: 0.39252
typography_spectrum: 0.57087
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73738239-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#fdfdfe'
    - '#484943'
    - '#cdbfbe'
    - '#9e8c82'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
