name: 'Carson Man!'
favicon: null
layout_spectrum: 0.9539190835785121
typography_spectrum: 0.14106
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060606'
    - '#fe0f26'
    - '#7a5c49'
    - '#bac3c8'
    - '#0043ad'
  brandStrength: 0.4684717352502048
  lightness: 0.17282296414487064
  saturation: 0.08957405062392354
  rhythmicContrast: 0.7442065281793475
purpose: []
