name: 'Carson Man!'
favicon: null
layout_spectrum: 0.67577
typography_spectrum: 0.14106
title: Keeping up with Carson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f3f3'
    - '#49a7f5'
    - '#060606'
    - '#2b6e2a'
    - '#f43640'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
