name: 'Carson Man!'
favicon: null
layout_spectrum: 1
typography_spectrum: 0.85388
title: Keeping up with Carson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#65a4cd'
    - '#fe0d00'
    - '#ffffff'
    - '#000000'
    - '#00ffff'
  brandStrength: 0
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
