name: 'Carson Man!'
favicon: null
layout_spectrum: 0.50271
typography_spectrum: 0.14106
title: Keeping up with Carson
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#121212'
    - '#8eb7ee'
    - '#707737'
    - '#4d433a'
  brandStrength: 0.0625
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
